#!/bin/bash

FILE=/opt/ercole-agent/config.json
if [[ -f "$FILE" ]]
    then
        rm -r /opt/ercole-agent/tmp
    else
        mv /opt/ercole-agent/tmp/config.json /opt/ercole-agent
fi

echo "[Unit]
Description=The Ercole Agent retrieves information about Oracle DB instances
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=1
User=ercole
WorkingDirectory=/opt/ercole-agent
ExecStart=/opt/ercole-agent/ercole-agent

[Install]
WantedBy=multi-user.target" > /etc/systemd/system/ercole-agent.service ;


echo "/var/log/ercole-agent.log {
    missingok
    notifempty
    create 0600 ercole root
    rotate 6
    monthly
}" > /etc/logrotate.d/ercole-agent

'' >> /opt/ercole-agent/.dbs_group
'' >> /opt/ercole-agent/.cell_group
'' >> /opt/ercole-agent/.ibs_group_EMPTY

systemctl start ercole-agent.service ;
systemctl enable ercole-agent.service ;