#!/bin/bash

getent passwd ercole >/dev/null || \
    useradd -r -d /home/ercole-agent -m -s /bin/bash \
    -c "Ercole agent user" ercole
getent passwd ercole >/dev/null || \
    useradd -r -d /home/ercole-agent -m -s /bin/bash \
    -c "Ercole agent user" ercole
getent passwd ercole >/dev/null || \
    useradd -r -d /home/ercole-agent -m -s /bin/bash \
    -c "Ercole agent user" ercole
getent passwd ercole >/dev/null || \
    useradd -r -d /home/ercole-agent -m -s /bin/bash \
    -c "Ercole agent user" ercole

if getent group oinstall >/dev/null; then
    usermod -aG oinstall ercole
fi

if getent group dba >/dev/null; then
    usermod -aG dba ercole
fi

if getent group mysql >/dev/null; then
    usermod -aG mysql ercole
fi